### PR TITLE
Add the URL hash to enable hipchat preview.

### PR DESCRIPTION
**Pull request by 178inaba**
Hack to enable the image preview of hipchat.

hipchat

### CODE REVIEW

**Comment by 178inaba** [comment]
Thanks for the reply!

Can detect the **hipchat** in `robot.adapterName`.
https://github.com/github/hubot/blob/master/src/robot.coffee#L70

`robot.adapterName` is user input option.
It may uppercase and lowercase letters are mixed.

```console
$ bin/hubot -a hipchat # robot.adapterName == "hipchat"
$ bin/hubot -a HipChat # robot.adapterName == "HipChat"
```

So use the `toLowerCase()`.

Test hipchat adapter:

test-hipchat

Test shell adapter:

```console
bot> bot qr gen hello
bot> https://api.qrserver.com/v1/create-qr-code/?data=hello&size=128x128
```

**Comment by 178inaba** [comment]
Happy New Year! :tada:

Thank you review!
I agree with your review.

* Added `adapterHack` function and `makeUrl` function.
* Used the [hubot-test-helper](https://github.com/mtsmfm/hubot-test-helper) for testing.

This PR for passed the test.
https://travis-ci.org/178inaba/QR-Generator/builds/187956077

**Comment by eelcokoelewijn** [comment]
178inaba Thanks for getting all the changes done. I'm wondering if you would like to maintain this original repository for the qr- generator. I'm willing to transfer it to you, I'm currently not maintaining or using it. What do you think?

**Comment by 178inaba** [comment]
I routinely use hubot-qr-generator.
This script is useful!
https://www.npmjs.com/package/hubot-qr-generator

If it is difficult for you to maintain this script, I can maintain it.
In that case, I am glad if you can also have the authority to publish to npm!

My npm account:
https://www.npmjs.com/~178inaba

**Comment by eelcokoelewijn** [comment]
Hi Inaba,

I made you owner of the npm package, you should be able to publish new versions of the package. Also tried to transfer the git repository to you, this didn’t workout because you already have the QR-Generator repository forked… I think it’s a name conflict, so if it’s possible for you to rename the forked QR-Generator repository I will give it another try. Also merged your changes back into the repository.

Let me know when you changed the repository name on github.

Eelco

**Comment by 178inaba** [comment]
Hi Eelco,

https://help.github.com/articles/about-repository-transfers/
> The target account must not have a repository with the same name, or a fork in the same network.

Apparently, it seems that you can not have the fork itself in the transfer target account.
So I deleted the fork.
I think that you can transfer the repository!

Inaba

**Comment by eelcokoelewijn** [comment]
Hello!

You should now have a transfer request for the QR-Generator repository on github.com <http://github.com/>. I think you need to accept the transfer request and you should be owner of the repo. 
Did you check if you are owner of the npm package? If you have everything you need then you can remove me as owner of the npm package.

Happy coding!

Eelco

**Comment by 178inaba** [comment]
Hi Eelco,

Thanks for the repository transfer!
I accepted the transfer!

We also checked ownership of npm and made a new version available.

Inaba

**Comment by eelcokoelewijn** [comment]
Great! Happy coding and will check the package now and then to see what improvements you made. Keep up the good work. 

Eelco

**Comment by 178inaba** [comment]
thx!

**Pull request merged**
